<h1>Categorias</h1>
<br />

<div style="width: 50%;">
	<table class="table table-hover">
		<tr>
			<th>ID</th>
			<th>Nome</th>
			<th colspan="2" style="text-align: center">Ação</th>
		</tr>

		<?php foreach ($this->categorias as $categoria) { ?>
			<tr>
				<td><?php echo $categoria->getId(); ?></td>
				<td><?php echo $categoria->getNome(); ?></td>
				<td>Editar</td>
				<td>Excluir</td>
			</tr>	
		<?php } ?>
	</table>

	<?php echo $this->paginationControl($this->categorias, 'Sliding', 'paginator'); ?>
</div>

